import type { Project, Task, Agent, Prompt, Skill } from '@/types';

// Mock Project
export const mockProject: Project = {
  id: 'demo-wallie',
  name: 'Wallie',
  path: '/Users/demo/projects/wallie',
  status: 'running',
  lastOpened: new Date(),
  createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000), // 7 days ago
  description: 'AI-powered personal finance assistant',
  stats: {
    totalTasks: 15,
    completedTasks: 8,
    totalPrompts: 12,
    sentPrompts: 7,
    tokensUsed: 245000,
    lastActivity: new Date(),
  },
};

// Mock Tasks
export const mockTasks: Task[] = [
  {
    id: 'task-1',
    title: 'Setup project structure',
    description: 'Initialize the project with React, TypeScript, and Vite',
    status: 'done',
    priority: 'high',
    phase: 'Phase 1 - Foundation',
    assignedAgent: 'orchestrator',
    estimatedTokens: 5000,
    actualTokens: 4200,
    startedAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000),
    completedAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000),
    tags: ['setup', 'foundation'],
  },
  {
    id: 'task-2',
    title: 'Create component library',
    description: 'Build reusable UI components following design system',
    status: 'done',
    priority: 'high',
    phase: 'Phase 1 - Foundation',
    assignedAgent: 'frontend',
    estimatedTokens: 15000,
    actualTokens: 18500,
    startedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    completedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
    tags: ['ui', 'components'],
  },
  {
    id: 'task-3',
    title: 'Implement authentication flow',
    description: 'Setup OAuth2 authentication with Google and Apple',
    status: 'done',
    priority: 'critical',
    phase: 'Phase 2 - Core Features',
    assignedAgent: 'backend',
    estimatedTokens: 12000,
    actualTokens: 11800,
    startedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
    completedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    tags: ['auth', 'security'],
  },
  {
    id: 'task-4',
    title: 'Build transaction parser',
    description: 'Parse bank statements and categorize transactions',
    status: 'done',
    priority: 'high',
    phase: 'Phase 2 - Core Features',
    assignedAgent: 'backend',
    estimatedTokens: 20000,
    actualTokens: 22000,
    startedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    completedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    tags: ['parsing', 'data'],
  },
  {
    id: 'task-5',
    title: 'Create dashboard visualizations',
    description: 'Build charts and graphs for spending insights',
    status: 'done',
    priority: 'medium',
    phase: 'Phase 2 - Core Features',
    assignedAgent: 'frontend',
    estimatedTokens: 18000,
    actualTokens: 17500,
    startedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    completedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    tags: ['charts', 'visualization'],
  },
  {
    id: 'task-6',
    title: 'Implement budget tracking',
    description: 'Allow users to set and track budget goals',
    status: 'done',
    priority: 'high',
    phase: 'Phase 3 - User Features',
    assignedAgent: 'frontend',
    estimatedTokens: 14000,
    actualTokens: 13200,
    startedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    completedAt: new Date(Date.now() - 12 * 60 * 60 * 1000),
    tags: ['budget', 'tracking'],
  },
  {
    id: 'task-7',
    title: 'Add AI spending insights',
    description: 'Use GPT-4 to provide personalized spending recommendations',
    status: 'done',
    priority: 'high',
    phase: 'Phase 3 - User Features',
    assignedAgent: 'backend',
    estimatedTokens: 25000,
    actualTokens: 28000,
    startedAt: new Date(Date.now() - 10 * 60 * 60 * 1000),
    completedAt: new Date(Date.now() - 4 * 60 * 60 * 1000),
    tags: ['ai', 'insights'],
  },
  {
    id: 'task-8',
    title: 'Build notification system',
    description: 'Push notifications for budget alerts and insights',
    status: 'done',
    priority: 'medium',
    phase: 'Phase 3 - User Features',
    assignedAgent: 'backend',
    estimatedTokens: 10000,
    actualTokens: 9800,
    startedAt: new Date(Date.now() - 3 * 60 * 60 * 1000),
    completedAt: new Date(Date.now() - 1 * 60 * 60 * 1000),
    tags: ['notifications', 'alerts'],
  },
  {
    id: 'task-9',
    title: 'Implement recurring transactions',
    description: 'Detect and manage recurring subscriptions',
    status: 'running',
    priority: 'high',
    phase: 'Phase 4 - Polish',
    assignedAgent: 'backend',
    estimatedTokens: 12000,
    startedAt: new Date(Date.now() - 30 * 60 * 1000),
    tags: ['subscriptions', 'recurring'],
  },
  {
    id: 'task-10',
    title: 'Add export functionality',
    description: 'Export data to CSV and PDF formats',
    status: 'queued',
    priority: 'medium',
    phase: 'Phase 4 - Polish',
    dependencies: ['task-9'],
    tags: ['export', 'data'],
  },
  {
    id: 'task-11',
    title: 'Write unit tests',
    description: 'Comprehensive test coverage for core functions',
    status: 'pending',
    priority: 'high',
    phase: 'Phase 5 - Testing',
    assignedAgent: 'qa',
    estimatedTokens: 20000,
    tags: ['testing', 'quality'],
  },
  {
    id: 'task-12',
    title: 'Integration tests',
    description: 'End-to-end testing for critical user flows',
    status: 'pending',
    priority: 'high',
    phase: 'Phase 5 - Testing',
    dependencies: ['task-11'],
    tags: ['testing', 'e2e'],
  },
  {
    id: 'task-13',
    title: 'Code review and refactor',
    description: 'Review code quality and optimize performance',
    status: 'pending',
    priority: 'medium',
    phase: 'Phase 5 - Testing',
    assignedAgent: 'reviewer',
    estimatedTokens: 15000,
    tags: ['review', 'refactor'],
  },
  {
    id: 'task-14',
    title: 'Performance optimization',
    description: 'Optimize bundle size and runtime performance',
    status: 'pending',
    priority: 'medium',
    phase: 'Phase 6 - Ship',
    dependencies: ['task-13'],
    tags: ['performance', 'optimization'],
  },
  {
    id: 'task-15',
    title: 'Deploy to production',
    description: 'Setup CI/CD and deploy to Vercel',
    status: 'pending',
    priority: 'critical',
    phase: 'Phase 6 - Ship',
    dependencies: ['task-14'],
    tags: ['deploy', 'production'],
  },
];

// Mock Agents
export const mockAgents: Agent[] = [
  {
    id: 'agent-orchestrator',
    type: 'orchestrator',
    name: 'Maestro',
    status: 'active',
    currentTask: 'task-9',
    tokensUsed: 45000,
    startedAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000),
  },
  {
    id: 'agent-frontend',
    type: 'developer',
    name: 'Pixel',
    status: 'waiting',
    tokensUsed: 68000,
    startedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
  },
  {
    id: 'agent-backend',
    type: 'developer',
    name: 'Logic',
    status: 'active',
    currentTask: 'task-9',
    tokensUsed: 82000,
    startedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
  },
  {
    id: 'agent-qa',
    type: 'qa',
    name: 'Scout',
    status: 'idle',
    tokensUsed: 15000,
    startedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
  },
  {
    id: 'agent-reviewer',
    type: 'reviewer',
    name: 'Sage',
    status: 'idle',
    tokensUsed: 12000,
    startedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
  },
];

// Mock Prompts
export const mockPrompts: Prompt[] = [
  {
    id: 'prompt-1',
    taskId: 'task-1',
    title: 'Initialize project structure',
    content: 'Create a new React + TypeScript project using Vite. Setup the folder structure according to best practices.',
    category: 'implementation',
    status: 'completed',
    createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000),
    sentAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000),
    response: 'Created project structure with src/, components/, hooks/, and utils/ directories.',
  },
  {
    id: 'prompt-2',
    taskId: 'task-2',
    title: 'Create Button component',
    content: 'Build a reusable Button component with variants: primary, secondary, ghost. Include loading state and icon support.',
    category: 'implementation',
    status: 'completed',
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    sentAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
  },
  {
    id: 'prompt-3',
    taskId: 'task-3',
    title: 'Implement OAuth flow',
    content: 'Setup OAuth2 authentication with Google provider. Handle token refresh and session management.',
    category: 'implementation',
    status: 'completed',
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
    sentAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
  },
  {
    id: 'prompt-4',
    taskId: 'task-4',
    title: 'Review transaction parser',
    content: 'Review the transaction parsing logic for edge cases and potential improvements.',
    category: 'review',
    status: 'completed',
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    sentAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
  },
  {
    id: 'prompt-5',
    taskId: 'task-9',
    title: 'Detect recurring transactions',
    content: 'Implement algorithm to detect recurring transactions based on amount, merchant, and frequency patterns.',
    category: 'implementation',
    status: 'sent',
    createdAt: new Date(Date.now() - 30 * 60 * 1000),
    sentAt: new Date(Date.now() - 25 * 60 * 1000),
  },
  {
    id: 'prompt-6',
    taskId: 'task-11',
    title: 'Write unit tests for parser',
    content: 'Create comprehensive unit tests for the transaction parser module.',
    category: 'test',
    status: 'pending',
    createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000),
  },
  {
    id: 'prompt-7',
    taskId: 'task-13',
    title: 'Debug memory leak',
    content: 'Investigate and fix the memory leak in the chart rendering component.',
    category: 'debug',
    status: 'pending',
    createdAt: new Date(),
  },
];

// Mock Skills
export const mockSkills: Skill[] = [
  {
    id: 'skill-1',
    name: 'genius-orchestrator',
    description: 'Multi-agent task orchestration and delegation',
    enabled: true,
    path: '.claude/skills/genius-orchestrator.md',
    category: 'core',
    triggers: ['start', 'orchestrate', 'delegate'],
    lastUsed: new Date(Date.now() - 1 * 60 * 60 * 1000),
  },
  {
    id: 'skill-2',
    name: 'genius-reviewer',
    description: 'Code review and quality assurance',
    enabled: true,
    path: '.claude/skills/genius-reviewer.md',
    category: 'core',
    triggers: ['review', 'check', 'validate'],
    lastUsed: new Date(Date.now() - 3 * 60 * 60 * 1000),
  },
  {
    id: 'skill-3',
    name: 'genius-debugger',
    description: 'Intelligent debugging and error resolution',
    enabled: true,
    path: '.claude/skills/genius-debugger.md',
    category: 'core',
    triggers: ['debug', 'fix', 'error'],
  },
  {
    id: 'skill-4',
    name: 'react-component',
    description: 'Generate React components with TypeScript',
    enabled: true,
    path: '.claude/skills/react-component.md',
    category: 'integration',
    triggers: ['component', 'react'],
    lastUsed: new Date(Date.now() - 5 * 60 * 60 * 1000),
  },
  {
    id: 'skill-5',
    name: 'test-generator',
    description: 'Generate unit and integration tests',
    enabled: true,
    path: '.claude/skills/test-generator.md',
    category: 'integration',
    triggers: ['test', 'spec'],
  },
  {
    id: 'skill-6',
    name: 'api-builder',
    description: 'Build REST and GraphQL APIs',
    enabled: true,
    path: '.claude/skills/api-builder.md',
    category: 'integration',
    triggers: ['api', 'endpoint'],
    lastUsed: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
  },
  {
    id: 'skill-7',
    name: 'database-designer',
    description: 'Design and manage database schemas',
    enabled: false,
    path: '.claude/skills/database-designer.md',
    category: 'integration',
    triggers: ['database', 'schema'],
  },
  {
    id: 'skill-8',
    name: 'custom-formatter',
    description: 'Custom code formatting rules',
    enabled: true,
    path: '.claude/skills/custom-formatter.md',
    category: 'custom',
    triggers: ['format'],
  },
  {
    id: 'skill-9',
    name: 'doc-generator',
    description: 'Generate documentation from code',
    enabled: false,
    path: '.claude/skills/doc-generator.md',
    category: 'custom',
    triggers: ['docs', 'readme'],
  },
  {
    id: 'skill-10',
    name: 'deploy-helper',
    description: 'Deployment configuration and automation',
    enabled: true,
    path: '.claude/skills/deploy-helper.md',
    category: 'custom',
    triggers: ['deploy', 'ci'],
  },
];

// Mock MCP Connections
export interface MCPConnection {
  id: string;
  name: string;
  type: 'stdio' | 'http';
  status: 'connected' | 'disconnected' | 'error';
  endpoint?: string;
  command?: string;
  lastPing?: Date;
  latency?: number;
}

export const mockMCPConnections: MCPConnection[] = [
  {
    id: 'mcp-1',
    name: 'Filesystem Server',
    type: 'stdio',
    status: 'connected',
    command: 'npx @anthropic/mcp-fs',
    lastPing: new Date(),
    latency: 12,
  },
  {
    id: 'mcp-2',
    name: 'GitHub Integration',
    type: 'http',
    status: 'connected',
    endpoint: 'http://localhost:3100/mcp/github',
    lastPing: new Date(),
    latency: 45,
  },
  {
    id: 'mcp-3',
    name: 'Database Tools',
    type: 'stdio',
    status: 'disconnected',
    command: 'npx @anthropic/mcp-postgres',
  },
  {
    id: 'mcp-4',
    name: 'Slack Notifications',
    type: 'http',
    status: 'error',
    endpoint: 'http://localhost:3101/mcp/slack',
    lastPing: new Date(Date.now() - 5 * 60 * 1000),
  },
];

// Mock Plan Data
export interface PlanPhase {
  id: string;
  name: string;
  description: string;
  status: 'completed' | 'in_progress' | 'pending';
  tasks: string[];
  progress: number;
}

export const mockPlanPhases: PlanPhase[] = [
  {
    id: 'phase-1',
    name: 'Phase 1 - Foundation',
    description: 'Setup project structure and core components',
    status: 'completed',
    tasks: ['task-1', 'task-2'],
    progress: 100,
  },
  {
    id: 'phase-2',
    name: 'Phase 2 - Core Features',
    description: 'Implement main application features',
    status: 'completed',
    tasks: ['task-3', 'task-4', 'task-5'],
    progress: 100,
  },
  {
    id: 'phase-3',
    name: 'Phase 3 - User Features',
    description: 'Build user-facing functionality',
    status: 'completed',
    tasks: ['task-6', 'task-7', 'task-8'],
    progress: 100,
  },
  {
    id: 'phase-4',
    name: 'Phase 4 - Polish',
    description: 'Refine and enhance the application',
    status: 'in_progress',
    tasks: ['task-9', 'task-10'],
    progress: 50,
  },
  {
    id: 'phase-5',
    name: 'Phase 5 - Testing',
    description: 'Comprehensive testing and review',
    status: 'pending',
    tasks: ['task-11', 'task-12', 'task-13'],
    progress: 0,
  },
  {
    id: 'phase-6',
    name: 'Phase 6 - Ship',
    description: 'Deploy to production',
    status: 'pending',
    tasks: ['task-14', 'task-15'],
    progress: 0,
  },
];
